import { Button, Flex, Input, Space, Typography } from "antd";
import type { ColumnsType } from "antd/es/table";
import BaseTable from "../../../components/base/BaseTable";

const { Text } = Typography;

type ReportRow = {
  key: string;
  reportId: string;
  reportType: string;
  period: string;
  generatedBy: string;
  generatedDate: string;
};

const data: ReportRow[] = [
  {
    key: "REP-001",
    reportId: "#REP-001",
    reportType: "Sales Summary",
    period: "Monthly",
    generatedBy: "Admin User",
    generatedDate: "2023-10-27",
  },
  {
    key: "REP-002",
    reportId: "#REP-002",
    reportType: "Inventory Audit",
    period: "Weekly",
    generatedBy: "Admin User",
    generatedDate: "2023-10-26",
  },
  {
    key: "REP-003",
    reportId: "#REP-003",
    reportType: "Waste Report",
    period: "Daily",
    generatedBy: "System Auto",
    generatedDate: "2023-10-25",
  },
];

const columns: ColumnsType<ReportRow> = [
  {
    title: "Report ID",
    dataIndex: "reportId",
    key: "reportId",
    render: (value: string) => <Text strong>{value}</Text>,
    width: 120,
  },
  {
    title: "Report Type",
    dataIndex: "reportType",
    key: "reportType",
    width: 160,
  },
  {
    title: "Period",
    dataIndex: "period",
    key: "period",
    width: 110,
  },
  {
    title: "Generated By",
    dataIndex: "generatedBy",
    key: "generatedBy",
    width: 150,
  },
  {
    title: "Generated Date",
    dataIndex: "generatedDate",
    key: "generatedDate",
    width: 160,
  },
  {
    title: "Actions",
    key: "actions",
    width: 160,
    render: () => (
      <Space>
        <Button size="small">View</Button>
        <Button size="small">Export</Button>
      </Space>
    ),
  },
];

function ReportTable() {
  const tableHeader = (
    <Flex justify="space-between" align="center">
      <div className="flex flex-col">
        <Text className="text-[11px] uppercase tracking-[0.12em] text-slate-400">
          Reports list
        </Text>
      </div>
      <div className="w-[200px]">
        <Input.Search
          placeholder="Search by report ID..."
          className="w-[320px]"
          allowClear
        />
      </div>
    </Flex>
  );

  return (
    <BaseTable
      title={() => tableHeader}
      columns={columns}
      dataSource={data}
      scroll={{ x: 860 }}
      cardClassName="!rounded-2xl shadow-[0_12px_28px_rgba(15,23,42,0.06)]"
    />
  );
}

export default ReportTable;
