spring.application.name=warehouse

# ===============================
# SERVER
# ===============================
server.port=9090 

# ===============================
# DATASOURCE - MYSQL
# ===============================
# spring.datasource.url=jdbc:mysql://localhost:3306/pharmacy_warehouse?useSSL=false&serverTimezone=UTC
spring.datasource.url=jdbc:mysql://localhost:3306/pharmacy_warehouse?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Sampro2k5@123

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

